spring:
  security:
    user:
      name: client
      password: client
  boot:
    admin:
      client:
        username: admin
        password: admin
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
        url:
          - http://localhost:8080
  application:
    name: spring-admin-client

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"


admin:
  param:
    name: "jmx.monitoring.tool.name"
    value: "appdynamics"



